[package]
name = "rust_ambilight"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
libwayshot = "0.8.0"
r-egl = "0.7.1"
r-egl-wayland = "0.7.1"
wayland-client = "0.31.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gbm = "0.18.0"

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
